spring:
  datasource:
    url: jdbc:h2:mem:empikdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/db.changelog-master.xml
    default-schema: public
  H2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

empik:
  github-url: 'https://api.github.com/users/'